config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :movements
  resources :essences

  authenticated :user do
    root 'movements#index', :as => "authenticated_root"
  end

  root 'welcome#index'

  mount API => '/'
end

app/models/movement.rb
class Movement < ActiveRecord::Base
	validates :name, presence: true
	validates :category, presence: true
	validates :amount, presence: true

	scope :category, -> (category) { where category: category }
	scope :user_id, -> (user) { where user_id: user }
	scope :movementType, -> (movementType) { where movementType: movementType }
	#scope :date, -> (year) { where('extract(year  from date) = ?', year) }
	#scope :date_year_month, -> (year, month) { where("strftime('%Y', date) = ? and strftime('%m', date) = ?", year, month) }
	scope :date_year_month, -> (year, month) { where("extract(year from date) = ? and extract(month from date) = ?", year, month) }

	# filterrific(
	#     available_filters: [
	#     	:date_year_month
	#     ]
	# )


	def self.find_all_by_date(yr, mth, user)
		if (yr.nil? || mth.nil?)
			Movement.date_year_month(Time.now.strftime("%Y"), Time.now.strftime("%m")).user_id(user)
		else
			Movement.date_year_month(yr, mth).user_id(user)
		end

	end

	def self.find_all_years
		#Model.select("distinct(extract(year from date))")
		#Movement.select("strftime('%Y', date)")

		@years = []

		Movement.pluck(:date).each do | year |
		  @years << year.strftime("%Y")
		end

		@years = @years.uniq
	end

	def self.find_all_years_by_user(user_id)

		@years = []

		Movement.user_id(user_id).pluck(:date).each do | year |
			@years << year.strftime("%Y")
		end

		@years = @years.uniq
	end

	def self.find_all_months
		#Model.select("distinct(extract(month from date))")
		#Movement.select("strftime('%m', date)")

		@months = []

		Movement.pluck(:date).each do | month |
		   @months << month.strftime("%m")
		end

		@months = @months.uniq.sort_by(&:to_i)
	end

	def self.find_all_months_by_user(user_id)

		@months = []

		Movement.user_id(user_id).pluck(:date).each do | month |
			@months << month.strftime("%m")
		end

		@months = @months.uniq.sort_by(&:to_i)
	end

	def self.compute_total(movements)
		@total = 0
		movements.order(:date).each do |movement|
			if (movement.movementType)
				@total = @total - movement.amount
			else 	
				@total = @total + movement.amount
			end	
		end	

		return @total
	end	

	def self.compute_cumulative_list(movements)

		sorted_movements = movements.order(:date);

		signed_movements = Array.new

		sorted_movements.each do |movement|
			m = Hash.new
		 	m[:date] = movement.date
		 	if (movement.movementType)
		 		m[:amount] = 0 - movement.amount
		 	else
		 		m[:amount] = 0 + movement.amount
		 	end

			signed_movements.push(m)
		 end



		grouped_movements = Hash.new(0)
		signed_movements.each do |movement|
			grouped_movements[movement[:date]] += movement[:amount]
		end

		cumulated_movements = Array.new()
		total = 0

		grouped_movements.each do |key, value|
		 	total += value
			cumulated_movements.push([key, total])
		end

		return cumulated_movements

	end	

	def self.find_all_names(user)
		Movement.user_id(user).pluck(:name).uniq
	end	

	def self.find_all_categories(user)
		Movement.user_id(user).pluck(:category).uniq
	end	
                   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user!

  def index
      @movements = Movement.find_all_by_date(params[:year], params[:month], current_user.id)

      @sorted_movements = @movements.order(date: :desc)
      @reverse_sorted_movements = @movements.order(date: :asc)

      if (params[:year].nil?)
        @selected_year = Time.now.strftime("%Y")
      else
        @selected_year = params[:year]
      end  

      if (params[:month].nil?)
        @selected_month = Time.now.strftime("%m")
      else
        @selected_month = params[:month]
      end   

      @total = Movement.compute_total(@movements)
      @cumulative_list = Movement.compute_cumulative_list(@movements)
  end


	def new
		@movement = Movement.new
  end

    def create
	  @movement = Movement.new(movement_params)
    @movement.user_id = current_user.id

    if @movement.save
      redirect_to movements_path
    else
      render 'new'
    end

	end

	def show
    @movement = Movement.find(params[:id])
	end

	
	def destroy
    @movement = Movement.find(params[:id])

    respond_to do |format|
      if @movement.destroy
        format.html { redirect_to movements_path }
        format.json { head :no_content, status: :ok }
        format.xml { head :no_content, status: :ok }
      else
        format.html {}
        format.json { render json: @movement.errors, status: :unprocessable_entity }
        format.xml { render xml: @movement.errors, status: :unprocessable_entity }
      end
    end

	end

	def edit
  	  @movement = Movement.find(params[:id])
	end

	def update
    @movement = Movement.find(params[:id])
 
    if @movement.update(movement_params)
    	redirect_to @movement
    else
     	render 'edit'
    end
  end 

	private
  	  def movement_params
  	  	if params[:movement][:movementType] == "output"
  	  		params[:movement][:movementType] = true
  	  	else
  	  		params[:movement][:movementType] = false
  	  	end		

        params.require(:movement).permit(:name, :category, :amount, :movementType, :date)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depensometre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Dépensomètre</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Essence", essences_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Editer profil", edit_user_registration_path, :method => :get %></li>
                    <li><%= link_to "Se déconnecter", destroy_user_session_path, :method => :delete %></li>
                </ul>
            </li>

          </ul>
        </div>
      </div>
    </nav>
    </br></br></br>
<% end %>

<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/movements/edit.html.erb
<%= form_for :movement, :html => {:class => "form-horizontal"} , url: movement_path(@movement), method: :patch do |f| %>

<fieldset>
  <legend>Editer mouvement</legend>

  <% if @movement.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@movement.errors.count, "error") %> prohibited this movement from being saved:</h3>
      <ul>
        <% @movement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Nom", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>  
  </div> 

  <div class="form-group">
    <%= f.label "Catégorie", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :category, :class => "form-control" %>
    </div>  
  </div> 

  <div class="form-group">
    <%= f.label "Montant", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10"> 
      <%= f.number_field :amount, :class => "form-control text_field", :step => 'any' %>
    </div>  
  </div> 

  <div class="form-group">
    <%= f.label "Type", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10"> 
      <div class="radio">
        <label>
          <%= f.radio_button :movementType, "output", :checked => @movement.movementType %>Dépense
        </label>
      </div>
      <div class="radio"> 
        <label> 
          <%= f.radio_button :movementType, "input", :checked => !@movement.movementType %>Rentrée
        </label>
      </div>  
    </div>  
  </div> 

  <div class="form-group">
    <%= f.label :date, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10"> 
      <%= f.date_select :date %>
    </div>  
  </div> 

  <div class="col-lg-10 col-lg-offset-2">
    <%= link_to 'Annuler', movements_path, class: "btn btn-default " %> <%= link_to 'Supprimer', movement_path(@movement),
                method: :delete, data: { confirm: 'Etes-vous sûr ?' } , class: "btn btn-primary"%> <%= f.submit "Enregistrer", class: "btn btn-primary"  %> 
  </div>
</fieldset>  
<% end %>

app/views/movements/index.html.erb
<%= javascript_include_tag "app/assets/javascripts/highcharts.js", "chartkick" %>


<h1 class="col-lg-8"><%= Date::MONTHNAMES[@selected_month.to_i] + ' ' + @selected_year %> </h1>

<div class="col-lg-4 box">
  <div class="box-container">
  <%= form_tag movements_path, :method => 'get' do %>
      <%= select_tag :month, options_for_select(Movement.find_all_months,:selected=> @selected_month), class: "month_select" %>
      <%= select_tag :year, options_for_select(Movement.find_all_years,:selected=> @selected_year), class: "year_select" %>
      <%= submit_tag "Sélectionner", :name => nil, class: "btn btn-primary select_button" %>
  <% end %>
  </div> 
</div>


<div class="col-lg-3 box">
  <div id="recap" class="box-container">
  <div class="recap_big"><%= @movements.size %></div>
  <div class="recap_small">Mouvements</div>
  <div class="recap_big"><%= @total %> €</div>
  <div class="recap_small">Total</div>

  <br />
  <%= link_to 'Nouveau mouvement', new_movement_path, class: "btn btn-primary add_button" %>
  </div> 
</div>

 
<div  class="col-lg-9 box">
  <div id="movements_container" class="box-container">
  <table class="table table-hover table-responsive">
    <tr>
      <th>Date</th>
      <th>Nom</th>
      <th>Catégorie</th>
      <th>Montant</th>
    </tr>
   
    <% @sorted_movements.each do |movement| %>
      <tr onclick="location.href='/movements/<%= movement.id %>/edit'" >
        <td><%= movement.date.strftime("%d/%m/%Y") %></td>
        <td><%= movement.name %></td>
        <td><%= movement.category %></td>
        <td class="<%= movement.movementType ? 'output' : 'input' %>">
          <%= if movement.movementType
            "-"
          else
            "+"
          end  %><%= movement.amount %> €
        </td>
      </tr>
    <% end %>
  </table>
  </div> 
</div>  

<div class="box col-lg-4">
  <div class="box-container">
  Total rentrées/dépenses
  <%= column_chart  [['Dépenses', @movements.movementType(true).sum(:amount)], ['Rentrées', @movements.movementType(false).sum(:amount)]] %>
  </div> 
</div>

<div class="box col-lg-4">
  <div class="box-container">
  Dépenses
  <%= pie_chart @movements.movementType(true).group(:name).sum(:amount) %>
  </div> 
</div>

<div class="box col-lg-4">
  <div class="box-container">
  Rentrées
  <%= pie_chart @movements.movementType(false).group(:name).sum(:amount) %>
  </div> 
</div>

<div class="box col-lg-12">
  <div class="box-container">
  Répartition des dépenses
  <br /><br />
  <%= column_chart @reverse_sorted_movements.movementType(true).group(:date).sum(:amount), stacked: true, :library => {:hAxis => {:format => "dd/mm/yyyy"}} %>
  </div> 
</div> 

<div class="box col-lg-12">
  <div class="box-container">
  Répartition des rentrées
  <br /><br />
  <%= column_chart @reverse_sorted_movements.movementType(false).group(:date).sum(:amount), stacked: true, :library => {:hAxis => {:format => "dd/mm/yyyy"}} %>
  </div> 
</div> 

<div class="box col-lg-12">
  <div class="box-container">
  Evolution des mouvements
  <br /><br />
  <%= line_chart @cumulative_list %>
  </div> 
</div> 

app/views/movements/new.html.erb
<%= form_for :movement, :html => {:class => "form-horizontal"} , url: movements_path do |f| %>

<fieldset>
  <legend>Nouveau mouvement</legend>

  <% if @movement.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@movement.errors.count, "error") %> prohibited this movement from being saved:</h3>
      <ul>
        <% @movement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Nom", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>  
  </div> 

  <div class="form-group">
    <%= f.label "Catégorie", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :category, :class => "form-control" %>
    </div>  
  </div> 

  <div class="form-group">
    <%= f.label "Montant", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10"> 
      <%= f.number_field :amount, :class => "form-control text_field", :step => 'any' %>
    </div>  
  </div> 

  <div class="form-group">
    <%= f.label "Type", :class => "col-lg-2 control-label" %>
    <div class="col-lg-10"> 
      <div class="radio">
        <label>
          <%= f.radio_button :movementType, "output", :checked => true %>Dépense
        </label>
      </div>
      <div class="radio"> 
        <label> 
          <%= f.radio_button :movementType, "input" %>Rentrée
        </label>
      </div>  
    </div>  
  </div> 

  <div class="form-group">
    <%= f.label :date, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10"> 
      <%= f.date_select :date %>
    </div>  
  </div> 

  <div class="col-lg-10 col-lg-offset-2">
    <%= link_to 'Annuler', movements_path, class: "btn btn-default" %> <%= f.submit "Enregristrer", class: "btn btn-primary"  %> 
  </div>
</fieldset>  
<% end %>

app/views/movements/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @movement.name %>
</p>
 
<p>
  <strong>Category:</strong>
  <%= @movement.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @movement.amount %>
</p>

<p>
  <strong>Type:</strong>
  <%= if @movement.movementType
  		"Dépense"
  	else
  		"Rentrée"
  	end	 %>
</p>

<p>
  <strong>Date:</strong>
  <%= @movement.date.strftime("%d/%m/%Y") %>
</p>


<%= link_to 'Back', movements_path, class: "btn btn-primary" %>
<%= link_to 'Edit', edit_movement_path(@movement), class: "btn btn-primary" %>
<%= link_to 'Supprimer', movement_path(@movement),
                method: :delete, data: { confirm: 'Etes-vous sûr ?' } , class: "btn btn-primary"%>

app/views/welcome/index.html.erb
<div class="col-md-8 col-md-offset-2" align="middle">

  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <div class="col-md-8 custom-large-title">
    Dépensomètre
  </div>

  <div class="col-md-8" align="left">
    </br></br>

    <%= render "devise/shared/signin" %>
  </div>

</div>